<?php if ($this->getReviewsCount()): ?>
    <div class="ratings right">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <div class="rating-links">
            <a href="<?php echo $this->getReviewsUrl() ?>"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></a>
            <span class="separator">|</span>
            <a class="fancybox" href="#review-popup"><?php echo $this->__('Add Your Review') ?></a>
        </div>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <a class="right fancybox" href="#review-popup"><?php echo $this->__('Review this product') ?></a>
<?php endif; ?>