<?php if ($this->hasValidGroup()): ?>
<div class="home-banner">
	<script>
		jQuery(document).ready(function() {
		    var owl = jQuery("#owl-hero");
		    owl.owlCarousel({
			    lazyLoad    : true,
				transitionStyle : "fade",
				autoPlay    : 3000,
				stopOnHover : true,
				navigation  : true,
				pagination  : true,
				paginationSpeed : 1000,
				goToFirstSpeed : 2000,
				singleItem  : true,
				autoHeight  : true,
				navigationText : ["<span><i class='fa fa-chevron-left'></i></span>","<span><i class='fa fa-chevron-right'></i></span>"]
		    }); 
    	});
	</script>
	
	<?php $group = $this->getGroup() ?>
	<?php $banners = $this->getBanners() ?>
	<div id="owl-hero" class="owl-carousel">     
		<?php foreach($banners as $banner): ?>
			<div class="item">				
				<?php if ($banner->getId() == 7):?>
				    	<!-- Daily deal Banners -->
						<img class="lazyOwl" 
						data-src="<?php echo $this->getSkinUrl('images/slider-bg.jpg') ?>" 
						src="<?php echo $this->getSkinUrl('images/slider-bg.jpg') ?>" 
						alt="">
						<div class="owl-hero-content">
							<?php $promotions = Mage::getModel('catalogrule/rule')->getActiveDailydealPromotions();?>					
							<?php foreach ($promotions as $promotion):?> 
							<?php echo $this->getLayout()->createBlock('dailydeal/promotion')->setPromotion($promotion)->getStaticBlock();?>
							<?php break;?>
							<?php endforeach; ?>
						</div>
						<!-- END Daily deal Banners -->
				<?php else:?>
				<?php if ($banner->hasUrl()): ?>
					<a href="<?php echo $banner->getUrl() ?>" title="<?php echo $this->escapeHtml($banner->getTitle()) ?>" <?php if ($banner->getUrlTarget()): ?> target="<?php echo $banner->getUrlTarget() ?>"<?php endif; ?>>		
				<?php endif; ?>
				    <img class="lazyOwl" src="<?php echo $banner->getImageUrl() ?>" data-src="<?php echo $banner->getImageUrl() ?>" alt="<?php echo $this->escapeHtml($banner->getAltText()) ?>">
					<?php if ($banner->hasUrl()): ?></a><?php endif; ?>
                    <?php if ($banner->hasHtml()): ?><?php echo $banner->getHtml() ?><?php endif; ?>
				<?php endif;?>				
			</div><!-- END Item -->
		<?php endforeach; ?>		
	</div>				
</div><!--  End Home banner	 -->
<?php endif; ?>