<?php if($this->getCollection()->getSize()): ?>
<div class="toolbar">
        <div class="amount">
            <?php if($this->getLastPageNum()>1): ?>
                <?php echo $this->__('Showing %s-%s of %s items', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
            <?php else: ?>
                <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
            <?php endif; ?>
        </div>

        <ul class="limiter">
	        <li>View</li>
			<?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
			    <li><a <?php if($this->isLimitCurrent($_key)): ?>class="active"<?php endif ?> href="<?php echo $this->getLimitUrl($_key) ?>"><?php echo $_limit ?></a> <span>/</span></li>
            <?php endforeach; ?>
        </ul>

        <?php echo $this->getPagerHtml() ?>


    <?php if( $this->isExpanded() ): ?>
        <?php if( $this->isEnabledViewSwitcher() ): ?>
       
            <?php $_modes = $this->getModes(); ?>
            <?php if($_modes && count($_modes)>1): ?>
             <p class="view-mode">
            <label><?php echo $this->__('View as') ?>:</label>
            <?php foreach ($this->getModes() as $_code=>$_label): ?>
                <?php if($this->isModeActive($_code)): ?>
                    <strong title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></strong>&nbsp;
                <?php else: ?>
                    <a href="<?php echo $this->getModeUrl($_code) ?>" title="<?php echo $_label ?>" class="<?php echo strtolower($_code); ?>"><?php echo $_label ?></a>&nbsp;
                <?php endif; ?>
            <?php endforeach; ?>
            </p>
            <?php endif; ?>
        
        <?php endif; ?>
    
        <div class="sort-by">
            <label><?php echo $this->__('Sort by') ?></label>
            <select onchange="setLocation(this.value)">
            <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
                <option value="<?php echo $this->getOrderUrl($_key, 'asc') ?>"<?php if($this->isOrderCurrent($_key)): ?> selected="selected"<?php endif; ?>>
                    <?php echo $this->__($_order) ?>
                </option>
            <?php endforeach; ?>
            </select>
            <?php if($this->getCurrentDirection() == 'desc'): ?>
                <a href="<?php echo $this->getOrderUrl(null, 'asc') ?>" title="<?php echo $this->__('Set Ascending Direction') ?>"><i class="fa fa-sort-amount-asc"></i></a>
            <?php else: ?>
                <a href="<?php echo $this->getOrderUrl(null, 'desc') ?>" title="<?php echo $this->__('Set Descending Direction') ?>"><i class="fa fa-sort-amount-desc"></i></a>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
<?php endif ?>
