<div id="register" style="display:none">	
	<h4 class="modal-title">Register<a class="close-modal" href="javascript:void(0);" onclick="jQuery.fancybox.close();"><i class="fa fa-times-circle"></i></a></h4>
	
<div class="modal-content account-create-popup cf">

<?php echo $this->getChildHtml('form_fields_before')?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate">
<input type="hidden" name="success_url" value="<?php echo $this->getSuccessUrl() ?>" />
<input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />

	<ul class="form-list">                	        
		<li>
		<label class="required" for="firstname">First Name<i>*</i></label>
		<input type="text" class="input-text required-entry" maxlength="255" title="First Name" value="" name="firstname" id="firstname">
		</li>
		         
		<li>
		<label class="required" for="lastname">Last Name<i>*</i></label>
		<input type="text" class="input-text required-entry" maxlength="255" title="Last Name" value="" name="lastname" id="lastname">
		</li>
		
		<li>
		<label class="required"for="email_address"><?php echo $this->__('Email Address') ?><i>*</i></label>
		<input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getFormData()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
		</li>
		
		<li>
		<label for="password" class="required"><?php echo $this->__('Password') ?><i>*</i></label>
		<input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
		</li>
		
		<li>
		<label for="confirmation" class="required"><?php echo $this->__('Re-type Password') ?><i>*</i></label>
		<input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" />
		</li>
		                
		<?php /*
		if ($this->isNewsletterEnabled()): ?>
		<li class="control">
		<div class="input-box">
		<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed"<?php if($this->getFormData()->getIsSubscribed()): ?> checked="checked"<?php endif; ?> class="checkbox" />
		</div>
		<label for="is_subscribed"><?php echo $this->__('Sign Up for Newsletter') ?></label>
		</li>
		<?php endif
		*/ ?>
		<?php echo $this->getChildHtml('form.additional.info'); ?>
		<?php echo $this->getChildHtml('persistent.remember.me'); ?>
		
		
		<?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
		<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button">And we're done!</button>
		<?php if (Mage::helper('checkout')->isContextCheckout()): ?>
		<input name="context" type="hidden" value="checkout" />
		<?php endif; ?>
	</ul>


    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>

</div><!-- END modal content -->
</div>