<table width="90%" class="header-invoice-table" cellspacing="10">
    <tr>
        <td colspan="2" style="text-align: center">
            <img src="<?php echo $this->getSkinUrl('images/malaysia-logo.png') ?>" alt="logo" />
        </td>
    </tr>
    <tr>
        <td colspan="2" style="margin-top: 10px; text-align: center; font-weight: bold"><?php echo $this->getCompanyName() ?></td>
    </tr>
    <tr>
        <td colspan="2" style="margin-top: 10px; margin-bottom: 20px; text-align: center;"><?php echo $this->getCompanyRegistrationText() ?></td>
    </tr>
    <tr>
        <td colspan="2" style="margin-top: 10px; text-align: center; font-weight: bold; text-transform: uppercase"><?php echo $this->getCompanyAddress() ?></td>
    </tr>
    <tr>
        <td style="font-weight: bold; text-align: right"><?php echo $this->getTelephoneNumber() ?></td>
        <td style="font-weight: bold; text-align: left"><?php echo $this->getFaxNumber() ?></td>
    </tr>
    <tr>
        <td colspan="2" style="margin-top: 10px; text-align: center; font-size: 1.4em; text-transform: uppercase"><?php echo $this->getGstRegistrationText() ?></td>
    </tr>
</table>
<hr />
<table width="90%" class="header-subinvoice-table" cellspacing="10">
    <tr>
        <td colspan="3">
            <?php echo date('d F Y', strtotime($this->getInvoice()->getCreatedAt())); ?>
        </td>
    </tr>
    <tr>
        <td><?php echo $this->getLibidexAddressHtml() ?></td>
        <td colspan="2" style="text-align: right; vertical-align: bottom">
            <?php echo $this->__('Shipment Ref: <strong>%s</strong>', $this->getInvoice()->getInvoiceReference()) ?>
        </td>
    </tr>
</table>