<header id="scroll-top">	
	<div class="top-bar">
	<div class="inner">
		<span class="welcome"><?php echo Mage::getStoreConfig('design/header/welcome');?></span>
		<ul class="social-links">
			<li><a href="<?php echo $this->getUrl('contact-us/') ?>">Contact us</a></li>
			<li><a href="https://www.facebook.com/pages/Libidex-Ltd/195911363755106" target="_blank"><i class="fa fa-facebook"></i></a></li>
			<li><a href="https://twitter.com/libidexltd" target="_blank"><i class="fa fa-twitter"></i></a></li>
			<li><a href="http://instagram.com/libidex" target="_blank"><i class="fa fa-instagram"></i></a></li>
		</ul>
	</div>
	</div>
	<div class="inner">		
		<ul class="head-left sf-menu dropdown currency">
			<?php if ($this->helper('customer')->isLoggedIn()):?><li class="welcome"><a href="<?php echo $this->getUrl('customer/account') ?>">Welcome <?php echo Mage::getSingleton('customer/session')->getCustomer()->getName();?></a></li><?php endif;?>
			<?php echo $this->getChildHtml('currency_apply') ?>
		</ul>		
		<div class="head-middle">
			<?php if ($this->getIsHomePage()):?>        
			<h1><a class="logo" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
			<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
			<?php else:?>
			<a class="logo" href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>">
			<img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
			<?php endif?>
		</div>		
		<ul class="head-right sf-menu dropdown account">
			<li class="subscribe_head_link"><a class="fancybox" href="#subscribe">Subscribe to our newsletter</a></li>
			<?php if ($this->helper('customer')->isLoggedIn()) :?>
			<li><a href="<?php echo $this->getUrl('customer/account/logout') ?>">Sign out</a></li>
			<li><a href="<?php echo $this->getUrl('customer/account') ?>">My Account <i class="fa fa-angle-down"></i></a>
				<ul>
					<li><a class="title" href="<?php echo $this->getUrl('customer/account') ?>">My Account</a></li>
					<li><a href="<?php echo $this->getUrl('customer/account') ?>">Dashboard</a></li>
					<li><a href="<?php echo $this->getUrl('customer/account/edit') ?>">Account information</a></li>
					<li><a href="<?php echo $this->getUrl('sales/order/history') ?>">My Orders</a></li>
					<li><a href="<?php echo $this->getUrl('wishlist') ?>">My Wishlist</a></li>
					<li><a href="<?php echo $this->getUrl('review/customer') ?>">My Reviews</a></li>								
				</ul>
			</li>
			<?php else:?>
			<li><a href="<?php echo $this->getUrl('customer/account/login') ?>">Sign in</a></li>
			<?php endif?>
		</ul>		
	</div><!-- End Inner -->	
	<nav><div class="inner">
		<button class="mmenu"><i class="fa fa-bars fa-lg"></i></button>
		<?php echo $this->getChildHtml('topMenu') ?>
		<ul class="secondary-nav sf-menu dropdown">
			<li class="site-search"><?php echo $this->getChildHtml('topSearch') ?></li>
			<li class="mobile-account"><a href="<?php echo $this->getUrl('customer/account') ?>"><i class="fa fa-user"></i></a></li>
			<li class="level-top exp-bag"><?php echo $this->getChildHtml('topCart'); ?></li>
			<li class="star-this">
			<?php if (!$this->helper('customer')->isLoggedIn()):?>			
				<a class="level-top" href="<?php echo $this->helper('wishlist')->getListUrl() ?>"><i class="fa fa-heart"></i> <span>0</span></a>
				<ul>
				<li class="title">0 items in wishlist. <a class="highlight-link" href="<?php echo $this->helper('wishlist')->getListUrl() ?>">Sign in</a> to create your list</li>			
				</ul>
			<?php else:?>
				<?php echo $this->getChildHtml('topWishlist'); ?>
			<?php endif;?>
			</li>
		</ul>	
	</div></nav>
</header>