<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AlsoViewed
 * @version    1.0.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<?php /** @var $this AW_AlsoViewed_Block_Products */ ?>
<?php if ($this->getEnabled() && $this->getAlsoViewedCollection()->getSize()): ?>
<div class="aw-box aw-base-mini aw-mini-related-items block">
    <div class="head">
        <h4><?php echo $this->__('Customers Who Viewed This Also Viewed') ?></h4>
    </div>
    <div class="aw-content"<?php if (Mage::helper('aw_alsoviewed')->checkVersion('1.4.1.0')) echo ' id="after1400"'; ?>>
        <p><strong><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" class="select-all-related"><?php echo $this->__('select all') ?></a></strong></p>
        <ol>
        <?php foreach($this->getAlsoViewedCollection() as $_item): ?>
        <?php $_item->setDoNotUseCategoryId(true); ?>
        <li<?php if($_item->isComposite() || !$_item->isSaleable()): ?> class="super-products"<?php endif; ?>>
            <div class="product-images">
            <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                <span class="checkbox-container">
                <?php if (!$_item->getRequiredOptions()): ?>
                    <input type="checkbox" class="aw-related-checkbox left" id="aw-related-checkbox<?php echo $_item->getId() ?>" name="aw_related_products[]" value="<?php echo $_item->getId() ?>" />
                <?php endif; ?>
                </span>
            <?php else: ?>
                <span class="checkbox-container">&nbsp;</span>
            <?php endif; ?>
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="50" height="50" /></a>
            </div>
            <div class="product-details">
                <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                <?php echo $this->getPriceHtml($_item, true); ?>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <p><a href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="aw-link-cart"><?php echo $this->__('Add to Wishlist') ?></a></p>
                <?php endif; ?>
            </div>
        </li>
        <?php endforeach ?>
        </ol>
    </div>
</div>
<script type="text/javascript">
(function() {
    var checkboxes = $$('.aw-related-checkbox'),
        labels = [
            '<?php echo $this->__('select all') ?>',
            '<?php echo $this->__('unselect all') ?>'
        ],
        allChecked = false;

    function collectCheckboxes() {
        var values = [];

        checkboxes.each(function(item) {
            if (item.checked)
                values.push(item.value);
        });

        if ($('related-products-field'))
            $('related-products-field').value = values.join(',');
    }

    Event.observe($$('.select-all-related')[0], 'click', function(event) {
        allChecked = !allChecked;
        checkboxes.each(function(checkbox) {
            checkbox.checked = allChecked;
            collectCheckboxes();
        });
        event.element().innerHTML = labels[allChecked + 0];
        Event.stop(event);
    });

    checkboxes.each(function(checkbox){
        $(checkbox).observe('click', collectCheckboxes);
    });
})();
</script>
<?php endif ?>