<a href="javascript:void(0)" class="level-top"><i class="fa fa-search"></i></a>
<?php $catalogSearchHelper = $this->helper('catalogsearch'); ?>
<form id="search_mini_form" action="<?php echo $catalogSearchHelper->getResultUrl() ?>" method="get">
	<div class="search-form">
		<input placeholder="Search entire shop..." id="search" type="text" name="<?php echo $catalogSearchHelper->getQueryParamName() ?>" value="" class="site-search-input" maxlength="<?php echo $catalogSearchHelper->getMaxQueryLength();?>" />
		<button type="submit" title="<?php echo $this->__('Search') ?>"><?php echo $this->__('Search') ?></button>
	</div>
	<script type="text/javascript">
	//<![CDATA[
	var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search entire shop...') ?>');
	//]]>
	</script>
</form>