<?php
$options[$i++] = array('value'=>'AF', 'label'=>'Afghanistan');
$options[$i++] = array('value'=>'AX', 'label'=>'Åland Islands');
$options[$i++] = array('value'=>'AL', 'label'=>'Albania');
$options[$i++] = array('value'=>'DZ', 'label'=>'Algeria');
$options[$i++] = array('value'=>'AS', 'label'=>'American Samoa');
$options[$i++] = array('value'=>'AD', 'label'=>'Andorra');
$options[$i++] = array('value'=>'AO', 'label'=>'Angola');
$options[$i++] = array('value'=>'AI', 'label'=>'Anguilla');
$options[$i++] = array('value'=>'AQ', 'label'=>'Antarctica');
$options[$i++] = array('value'=>'AG', 'label'=>'Antigua and Barbuda');
$options[$i++] = array('value'=>'AR', 'label'=>'Argentina');
$options[$i++] = array('value'=>'AM', 'label'=>'Armenia');
$options[$i++] = array('value'=>'AW', 'label'=>'Aruba');
$options[$i++] = array('value'=>'AU', 'label'=>'Australia');
$options[$i++] = array('value'=>'AT', 'label'=>'Austria');
$options[$i++] = array('value'=>'AZ', 'label'=>'Azerbaijan');
$options[$i++] = array('value'=>'BS', 'label'=>'Bahamas');
$options[$i++] = array('value'=>'BH', 'label'=>'Bahrain');
$options[$i++] = array('value'=>'BD', 'label'=>'Bangladesh');
$options[$i++] = array('value'=>'BB', 'label'=>'Barbados');
$options[$i++] = array('value'=>'BY', 'label'=>'Belarus');
$options[$i++] = array('value'=>'BE', 'label'=>'Belgium');
$options[$i++] = array('value'=>'BZ', 'label'=>'Belize');
$options[$i++] = array('value'=>'BJ', 'label'=>'Benin');
$options[$i++] = array('value'=>'BM', 'label'=>'Bermuda');
$options[$i++] = array('value'=>'BT', 'label'=>'Bhutan');
$options[$i++] = array('value'=>'BO', 'label'=>'Bolivia');
$options[$i++] = array('value'=>'BA', 'label'=>'Bosnia and Herzegovina');
$options[$i++] = array('value'=>'BW', 'label'=>'Botswana');
$options[$i++] = array('value'=>'BV', 'label'=>'Bouvet Island');
$options[$i++] = array('value'=>'BR', 'label'=>'Brazil');
$options[$i++] = array('value'=>'IO', 'label'=>'British Indian Ocean Territory');
$options[$i++] = array('value'=>'VG', 'label'=>'British Virgin Islands');
$options[$i++] = array('value'=>'BN', 'label'=>'Brunei');
$options[$i++] = array('value'=>'BG', 'label'=>'Bulgaria');
$options[$i++] = array('value'=>'BF', 'label'=>'Burkina Faso');
$options[$i++] = array('value'=>'BI', 'label'=>'Burundi');
$options[$i++] = array('value'=>'KH', 'label'=>'Cambodia');
$options[$i++] = array('value'=>'CM', 'label'=>'Cameroon');
$options[$i++] = array('value'=>'CA', 'label'=>'Canada');
$options[$i++] = array('value'=>'CV', 'label'=>'Cape Verde');
$options[$i++] = array('value'=>'KY', 'label'=>'Cayman Islands');
$options[$i++] = array('value'=>'CF', 'label'=>'Central African Republic');
$options[$i++] = array('value'=>'TD', 'label'=>'Chad');
$options[$i++] = array('value'=>'CL', 'label'=>'Chile');
$options[$i++] = array('value'=>'CN', 'label'=>'China');
$options[$i++] = array('value'=>'CX', 'label'=>'Christmas Island');
$options[$i++] = array('value'=>'CC', 'label'=>'Cocos (Keeling) Islands');
$options[$i++] = array('value'=>'CO', 'label'=>'Colombia');
$options[$i++] = array('value'=>'KM', 'label'=>'Comoros');
$options[$i++] = array('value'=>'CG', 'label'=>'Congo - Brazzaville');
$options[$i++] = array('value'=>'CD', 'label'=>'Congo - Kinshasa');
$options[$i++] = array('value'=>'CK', 'label'=>'Cook Islands');
$options[$i++] = array('value'=>'CR', 'label'=>'Costa Rica');
$options[$i++] = array('value'=>'CI', 'label'=>'Côte d’Ivoire');
$options[$i++] = array('value'=>'HR', 'label'=>'Croatia');
$options[$i++] = array('value'=>'CU', 'label'=>'Cuba');
$options[$i++] = array('value'=>'CY', 'label'=>'Cyprus');
$options[$i++] = array('value'=>'CZ', 'label'=>'Czech Republic');
$options[$i++] = array('value'=>'DK', 'label'=>'Denmark');
$options[$i++] = array('value'=>'DJ', 'label'=>'Djibouti');
$options[$i++] = array('value'=>'DM', 'label'=>'Dominica');
$options[$i++] = array('value'=>'DO', 'label'=>'Dominican Republic');
$options[$i++] = array('value'=>'EC', 'label'=>'Ecuador');
$options[$i++] = array('value'=>'EG', 'label'=>'Egypt');
$options[$i++] = array('value'=>'SV', 'label'=>'El Salvador');
$options[$i++] = array('value'=>'GQ', 'label'=>'Equatorial Guinea');
$options[$i++] = array('value'=>'ER', 'label'=>'Eritrea');
$options[$i++] = array('value'=>'EE', 'label'=>'Estonia');
$options[$i++] = array('value'=>'ET', 'label'=>'Ethiopia');
$options[$i++] = array('value'=>'FK', 'label'=>'Falkland Islands');
$options[$i++] = array('value'=>'FO', 'label'=>'Faroe Islands');
$options[$i++] = array('value'=>'FJ', 'label'=>'Fiji');
$options[$i++] = array('value'=>'FI', 'label'=>'Finland');
$options[$i++] = array('value'=>'FR', 'label'=>'France');
$options[$i++] = array('value'=>'GF', 'label'=>'French Guiana');
$options[$i++] = array('value'=>'PF', 'label'=>'French Polynesia');
$options[$i++] = array('value'=>'TF', 'label'=>'French Southern Territories');
$options[$i++] = array('value'=>'GA', 'label'=>'Gabon');
$options[$i++] = array('value'=>'GM', 'label'=>'Gambia');
$options[$i++] = array('value'=>'GE', 'label'=>'Georgia');
$options[$i++] = array('value'=>'DE', 'label'=>'Germany');
$options[$i++] = array('value'=>'GH', 'label'=>'Ghana');
$options[$i++] = array('value'=>'GI', 'label'=>'Gibraltar');
$options[$i++] = array('value'=>'GR', 'label'=>'Greece');
$options[$i++] = array('value'=>'GL', 'label'=>'Greenland');
$options[$i++] = array('value'=>'GD', 'label'=>'Grenada');
$options[$i++] = array('value'=>'GP', 'label'=>'Guadeloupe');
$options[$i++] = array('value'=>'GU', 'label'=>'Guam');
$options[$i++] = array('value'=>'GT', 'label'=>'Guatemala');
$options[$i++] = array('value'=>'GG', 'label'=>'Guernsey');
$options[$i++] = array('value'=>'GN', 'label'=>'Guinea');
$options[$i++] = array('value'=>'GW', 'label'=>'Guinea-Bissau');
$options[$i++] = array('value'=>'GY', 'label'=>'Guyana');
$options[$i++] = array('value'=>'HT', 'label'=>'Haiti');
$options[$i++] = array('value'=>'HM', 'label'=>'Heard Island and McDonald Islands');
$options[$i++] = array('value'=>'HN', 'label'=>'Honduras');
$options[$i++] = array('value'=>'HK', 'label'=>'Hong Kong SAR China');
$options[$i++] = array('value'=>'HU', 'label'=>'Hungary');
$options[$i++] = array('value'=>'IS', 'label'=>'Iceland');
$options[$i++] = array('value'=>'IN', 'label'=>'India');
$options[$i++] = array('value'=>'ID', 'label'=>'Indonesia');
$options[$i++] = array('value'=>'IR', 'label'=>'Iran');
$options[$i++] = array('value'=>'IQ', 'label'=>'Iraq');
$options[$i++] = array('value'=>'IE', 'label'=>'Ireland');
$options[$i++] = array('value'=>'IM', 'label'=>'Isle of Man');
$options[$i++] = array('value'=>'IL', 'label'=>'Israel');
$options[$i++] = array('value'=>'IT', 'label'=>'Italy');
$options[$i++] = array('value'=>'JM', 'label'=>'Jamaica');
$options[$i++] = array('value'=>'JP', 'label'=>'Japan');
$options[$i++] = array('value'=>'JE', 'label'=>'Jersey');
$options[$i++] = array('value'=>'JO', 'label'=>'Jordan');
$options[$i++] = array('value'=>'KZ', 'label'=>'Kazakhstan');
$options[$i++] = array('value'=>'KE', 'label'=>'Kenya');
$options[$i++] = array('value'=>'KI', 'label'=>'Kiribati');
$options[$i++] = array('value'=>'KW', 'label'=>'Kuwait');
$options[$i++] = array('value'=>'KG', 'label'=>'Kyrgyzstan');
$options[$i++] = array('value'=>'LA', 'label'=>'Laos');
$options[$i++] = array('value'=>'LV', 'label'=>'Latvia');
$options[$i++] = array('value'=>'LB', 'label'=>'Lebanon');
$options[$i++] = array('value'=>'LS', 'label'=>'Lesotho');
$options[$i++] = array('value'=>'LR', 'label'=>'Liberia');
$options[$i++] = array('value'=>'LY', 'label'=>'Libya');
$options[$i++] = array('value'=>'LI', 'label'=>'Liechtenstein');
$options[$i++] = array('value'=>'LT', 'label'=>'Lithuania');
$options[$i++] = array('value'=>'LU', 'label'=>'Luxembourg');
$options[$i++] = array('value'=>'MO', 'label'=>'Macau SAR China');
$options[$i++] = array('value'=>'MK', 'label'=>'Macedonia');
$options[$i++] = array('value'=>'MG', 'label'=>'Madagascar');
$options[$i++] = array('value'=>'MW', 'label'=>'Malawi');
$options[$i++] = array('value'=>'MY', 'label'=>'Malaysia');
$options[$i++] = array('value'=>'MV', 'label'=>'Maldives');
$options[$i++] = array('value'=>'ML', 'label'=>'Mali');
$options[$i++] = array('value'=>'MT', 'label'=>'Malta');
$options[$i++] = array('value'=>'MH', 'label'=>'Marshall Islands');
$options[$i++] = array('value'=>'MQ', 'label'=>'Martinique');
$options[$i++] = array('value'=>'MR', 'label'=>'Mauritania');
$options[$i++] = array('value'=>'MU', 'label'=>'Mauritius');
$options[$i++] = array('value'=>'YT', 'label'=>'Mayotte');
$options[$i++] = array('value'=>'MX', 'label'=>'Mexico');
$options[$i++] = array('value'=>'FM', 'label'=>'Micronesia');
$options[$i++] = array('value'=>'MD', 'label'=>'Moldova');
$options[$i++] = array('value'=>'MC', 'label'=>'Monaco');
$options[$i++] = array('value'=>'MN', 'label'=>'Mongolia');
$options[$i++] = array('value'=>'ME', 'label'=>'Montenegro');
$options[$i++] = array('value'=>'MS', 'label'=>'Montserrat');
$options[$i++] = array('value'=>'MA', 'label'=>'Morocco');
$options[$i++] = array('value'=>'MZ', 'label'=>'Mozambique');
$options[$i++] = array('value'=>'MM', 'label'=>'Myanmar (Burma)');
$options[$i++] = array('value'=>'NA', 'label'=>'Namibia');
$options[$i++] = array('value'=>'NR', 'label'=>'Nauru');
$options[$i++] = array('value'=>'NP', 'label'=>'Nepal');
$options[$i++] = array('value'=>'NL', 'label'=>'Netherlands');
$options[$i++] = array('value'=>'AN', 'label'=>'Netherlands Antilles');
$options[$i++] = array('value'=>'NC', 'label'=>'New Caledonia');
$options[$i++] = array('value'=>'NZ', 'label'=>'New Zealand');
$options[$i++] = array('value'=>'NI', 'label'=>'Nicaragua');
$options[$i++] = array('value'=>'NE', 'label'=>'Niger');
$options[$i++] = array('value'=>'NG', 'label'=>'Nigeria');
$options[$i++] = array('value'=>'NU', 'label'=>'Niue');
$options[$i++] = array('value'=>'NF', 'label'=>'Norfolk Island');
$options[$i++] = array('value'=>'MP', 'label'=>'Northern Mariana Islands');
$options[$i++] = array('value'=>'KP', 'label'=>'North Korea');
$options[$i++] = array('value'=>'NO', 'label'=>'Norway');
$options[$i++] = array('value'=>'OM', 'label'=>'Oman');
$options[$i++] = array('value'=>'PK', 'label'=>'Pakistan');
$options[$i++] = array('value'=>'PW', 'label'=>'Palau');
$options[$i++] = array('value'=>'PS', 'label'=>'Palestinian Territories');
$options[$i++] = array('value'=>'PA', 'label'=>'Panama');
$options[$i++] = array('value'=>'PG', 'label'=>'Papua New Guinea');
$options[$i++] = array('value'=>'PY', 'label'=>'Paraguay');
$options[$i++] = array('value'=>'PE', 'label'=>'Peru');
$options[$i++] = array('value'=>'PH', 'label'=>'Philippines');
$options[$i++] = array('value'=>'PN', 'label'=>'Pitcairn Islands');
$options[$i++] = array('value'=>'PL', 'label'=>'Poland');
$options[$i++] = array('value'=>'PT', 'label'=>'Portugal');
$options[$i++] = array('value'=>'PR', 'label'=>'Puerto Rico');
$options[$i++] = array('value'=>'QA', 'label'=>'Qatar');
$options[$i++] = array('value'=>'RE', 'label'=>'Réunion');
$options[$i++] = array('value'=>'RO', 'label'=>'Romania');
$options[$i++] = array('value'=>'RU', 'label'=>'Russia');
$options[$i++] = array('value'=>'RW', 'label'=>'Rwanda');
$options[$i++] = array('value'=>'BL', 'label'=>'Saint Barthélemy');
$options[$i++] = array('value'=>'SH', 'label'=>'Saint Helena');
$options[$i++] = array('value'=>'KN', 'label'=>'Saint Kitts and Nevis');
$options[$i++] = array('value'=>'LC', 'label'=>'Saint Lucia');
$options[$i++] = array('value'=>'MF', 'label'=>'Saint Martin');
$options[$i++] = array('value'=>'PM', 'label'=>'Saint Pierre and Miquelon');
$options[$i++] = array('value'=>'VC', 'label'=>'Saint Vincent and the Grenadines');
$options[$i++] = array('value'=>'WS', 'label'=>'Samoa');
$options[$i++] = array('value'=>'SM', 'label'=>'San Marino');
$options[$i++] = array('value'=>'ST', 'label'=>'São Tomé and Príncipe');
$options[$i++] = array('value'=>'SA', 'label'=>'Saudi Arabia');
$options[$i++] = array('value'=>'SN', 'label'=>'Senegal');
$options[$i++] = array('value'=>'RS', 'label'=>'Serbia');
$options[$i++] = array('value'=>'SC', 'label'=>'Seychelles');
$options[$i++] = array('value'=>'SL', 'label'=>'Sierra Leone');
$options[$i++] = array('value'=>'SG', 'label'=>'Singapore');
$options[$i++] = array('value'=>'SK', 'label'=>'Slovakia');
$options[$i++] = array('value'=>'SI', 'label'=>'Slovenia');
$options[$i++] = array('value'=>'SB', 'label'=>'Solomon Islands');
$options[$i++] = array('value'=>'SO', 'label'=>'Somalia');
$options[$i++] = array('value'=>'ZA', 'label'=>'South Africa');
$options[$i++] = array('value'=>'GS', 'label'=>'South Georgia and the South Sandwich Islands');
$options[$i++] = array('value'=>'KR', 'label'=>'South Korea');
$options[$i++] = array('value'=>'ES', 'label'=>'Spain');
$options[$i++] = array('value'=>'LK', 'label'=>'Sri Lanka');
$options[$i++] = array('value'=>'SD', 'label'=>'Sudan');
$options[$i++] = array('value'=>'SR', 'label'=>'Suriname');
$options[$i++] = array('value'=>'SJ', 'label'=>'Svalbard and Jan Mayen');
$options[$i++] = array('value'=>'SZ', 'label'=>'Swaziland');
$options[$i++] = array('value'=>'SE', 'label'=>'Sweden');
$options[$i++] = array('value'=>'CH', 'label'=>'Switzerland');
$options[$i++] = array('value'=>'SY', 'label'=>'Syria');
$options[$i++] = array('value'=>'TW', 'label'=>'Taiwan');
$options[$i++] = array('value'=>'TJ', 'label'=>'Tajikistan');
$options[$i++] = array('value'=>'TZ', 'label'=>'Tanzania');
$options[$i++] = array('value'=>'TH', 'label'=>'Thailand');
$options[$i++] = array('value'=>'TL', 'label'=>'Timor-Leste');
$options[$i++] = array('value'=>'TG', 'label'=>'Togo');
$options[$i++] = array('value'=>'TK', 'label'=>'Tokelau');
$options[$i++] = array('value'=>'TO', 'label'=>'Tonga');
$options[$i++] = array('value'=>'TT', 'label'=>'Trinidad and Tobago');
$options[$i++] = array('value'=>'TN', 'label'=>'Tunisia');
$options[$i++] = array('value'=>'TR', 'label'=>'Turkey');
$options[$i++] = array('value'=>'TM', 'label'=>'Turkmenistan');
$options[$i++] = array('value'=>'TC', 'label'=>'Turks and Caicos Islands');
$options[$i++] = array('value'=>'TV', 'label'=>'Tuvalu');
$options[$i++] = array('value'=>'UG', 'label'=>'Uganda');
$options[$i++] = array('value'=>'UA', 'label'=>'Ukraine');
$options[$i++] = array('value'=>'AE', 'label'=>'United Arab Emirates');
$options[$i++] = array('value'=>'GB', 'label'=>'United Kingdom');
$options[$i++] = array('value'=>'US', 'label'=>'United States');
$options[$i++] = array('value'=>'UY', 'label'=>'Uruguay');
$options[$i++] = array('value'=>'UM', 'label'=>'U.S. Minor Outlying Islands');
$options[$i++] = array('value'=>'VI', 'label'=>'U.S. Virgin Islands');
$options[$i++] = array('value'=>'UZ', 'label'=>'Uzbekistan');
$options[$i++] = array('value'=>'VU', 'label'=>'Vanuatu');
$options[$i++] = array('value'=>'VA', 'label'=>'Vatican City');
$options[$i++] = array('value'=>'VE', 'label'=>'Venezuela');
$options[$i++] = array('value'=>'VN', 'label'=>'Vietnam');
$options[$i++] = array('value'=>'WF', 'label'=>'Wallis and Futuna');
$options[$i++] = array('value'=>'EH', 'label'=>'Western Sahara');
$options[$i++] = array('value'=>'YE', 'label'=>'Yemen');
$options[$i++] = array('value'=>'ZM', 'label'=>'Zambia');
$options[$i++] = array('value'=>'ZW', 'label'=>'Zimbabwe');
