<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
		<ul>
			<?php if ($title = $this->getTitle()): ?>
				<li class="title">
					<h4 class="priority-1-heading white">
						<a href="<?php echo $this->getUrl('news-events') ?>"><?php echo $this->__($title) ?></a>
					</h4>
				</li>
			<?php endif; ?>

			<?php foreach($posts as $post): ?>
				<li class="item">
					<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>">
					<?php if ($post->getFeaturedImage()): ?>
						<img src="<?php echo $post->getFeaturedImage()->getFullSizeImage() ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
					<?php else:?>
						<img src="<?php echo $this->getSkinUrl('images/placeholders/blog.png') ?>" alt="<?php echo $this->escapeHtml($post->getPostTitle()) ?>"/>
					<?php endif; ?>
					</a>
					<h5><a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a></h5>
					<h6>Posted on <?php echo $post->getPostDate() ?></h6>
					<a class="home-posts-read-more" href="<?php echo $post->getPermalink() ?>">Read More</a>
				</li>
			<?php endforeach; ?>
		</ul>
<?php endif; ?>	