<?php $posts = $this->getPosts() ?>
<?php if (count($posts) > 0): ?>
<div class="block">
	<?php if ($title = $this->getTitle()): ?>
	<div class="block-title"><?php echo $this->__($title) ?></div>
	<?php endif; ?>
	<div class="block-content">
		<ul>
		<?php foreach($posts as $post): ?>
			<li class="item">
			<a href="<?php echo $post->getPermalink() ?>" title="<?php echo $this->htmlEscape($post->getPostTitle()) ?>"><?php echo $this->htmlEscape($post->getPostTitle()) ?></a>
			</li>
		<?php endforeach; ?>
		</ul>
	</div>
</div>
<?php endif; ?>	