<div class="product-downsell" style="display: none">
<?php if(count($this->getItemCollection()->getItems())): ?>
<script type="text/javascript">
  productAddToCartFromFormSubmit = function(button, url) {
      if (this.validator.validate()) {
          var form = this.form;
          var oldUrl = form.action;

          if (url) {
             form.action = url;
          }
          var e = null;
          try {
              // Bit of a hack to get around nested forms
              var a = document.createElement('form');
              a.setAttribute('action', url);
              a.setAttribute('method', 'POST');
              this.form = this.form.wrap(a);
              this.form.submit();
          } catch (e) {
          }
          this.form.action = oldUrl;
          if (e) {
              throw e;
          }

          if (button && button != 'undefined') {
              button.disabled = true;
          }
      }
  }    
</script>
<?php $_productCollection = $this->getItemCollection()->getItems(); ?>
<?php $_iterator = 0; ?>
<?php $_helper = $this->helper('catalog/output'); ?>



<ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <?php $p = Mage::getModel('catalog/product')->setStoreId(1)->load($_product->getId()); ?>
        <?php $_product = $p; ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <div action="<?php echo $this->getSubmitUrl($p) ?>" method="post" id="product_addtocart_form_<?php echo $_product->getId(); ?>"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
            <?php // Product description ?>
            <div class="product-shop-downsell">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php echo $this->getConfigurableHtml($_product); ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="productAddToCartForm<?php echo $_product->getId(); ?>.submit(this, '<?php echo $this->getSubmitUrl($p) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
            </div>
        </li>
        <script type="text/javascript">
          var productAddToCartForm<?php echo $_product->getId(); ?> = new VarienForm('product_addtocart_form_<?php echo $_product->getId(); ?>');
          productAddToCartForm<?php echo $_product->getId(); ?>.submit = productAddToCartFromFormSubmit.bind(productAddToCartForm<?php echo $_product->getId(); ?>);
        </script>
    <?php endforeach; ?>
</ol>
<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
<?php else: ?>

  <script type="text/javascript">
    $('show-latex').hide();
  </script>

<?php endif ?>
</div>