</div><!-- End Wrapper early -->
<h1 class="page-subtitle"><span class="inner"><?php echo $this->__('Shopping bag is empty') ?></span></h1>
<div class="wrapper"><!-- Begin Wrapper again -->
<div class="cart-empty">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php echo $this->getChildHtml('checkout_cart_empty_widget'); ?>
    <p><?php echo $this->__('You have no items in your shopping bag.') ?></p>
    <p><?php echo $this->__('Click <a class="highlight-link" href="%s">here</a> to continue shopping.', $this->getContinueShoppingUrl()) ?></p>
    <?php echo $this->getChildHtml('shopping.cart.table.after'); ?>
</div>
