<div class="block block-account">
	<h4 class="block-title central-line"><?php echo $this->__('My Account'); ?></h4>
    <div class="block-content">
        <ul class="my-account-nav">
            <?php $_links = $this->getLinks(); ?>
            <?php $_index = 1; ?>
            <?php // $_count = count($_links); ?>
            
            <?php $_count = count($_links); /* Add or Remove Account Left Navigation Links Here -*/            
				unset($_links['downloadable_products']); /* My Downloadable Products */
				unset($_links['recurring_profiles']); /* Recurring Profiles */
				unset($_links['billing_agreements']); /* Billing Agreements */
				unset($_links['OAuth Customer Tokens']); /* My Applications */
			?>

            <?php foreach ($_links as $_link): ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current">
                    <a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?><i class="fa fa-angle-right"></i></a>
                    </li>
                <?php else: ?>
                    <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?><i class="fa fa-angle-right"></i></a></li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>