<?php 
$swatches = $this->get_option_swatches();
$optionClass = Mage::getModel('productpagestep/attribute')->getOptionClassArray();
?>
<!-- GALATHEMES: COLOR SWATCHES -->
<script type="text/javascript">
	document.observe('dom:loaded', function() {
		try {
Element.prototype.triggerEvent = function(eventName)
{
    if (document.createEvent)
    {
        var evt = document.createEvent('HTMLEvents');
        evt.initEvent(eventName, true, true);

        return this.dispatchEvent(evt);
    }

    if (this.fireEvent)
        return this.fireEvent('on' + eventName);
}

function after_swatches_created()
{
            jQuery('.product-custom-option').each(function(i,el) {
                switch(el.tagName)
                {
                    case 'SELECT':
                        jQuery(el).change(function(e) { update_preview(e.currentTarget); });
			if (el.selectedIndex)
			{
				update_preview(el);
				// select a swatch
				if ($(el).up().down().hasClassName('swatches-container'))
				{
					$(el).up().down().select('img').each( function(i) {
						if (trim(i.title) == el.selectedOptions[0].label)
						{
							i.addClassName('current');
						}
					});
					$(el).up().down().select('a').each( function(i) {
						if (trim(i.innerText) == el.selectedOptions[0].label)
						{
							i.addClassName('current');
						}
					});
				}
				$(el).triggerEvent('change');
			}
                        break;
                    case 'INPUT':
                        jQuery(el).change(function(e) { update_preview(e.currentTarget); });
			if (el.checked)
			{
				update_preview(el);
				$(el).triggerEvent('change');
			}
                        break;
                }
            });
}
            function update_preview(el) {
                var preview = jQuery(el).closest('dd').find('.swatchPreview');
		var previewSrc = '';
                if (preview)
                {
                    if (el.tagName === 'SELECT') {
                        if (jQuery(el.up().down('.swatches-container')).hasClass("Colour"))
                        {
                            previewSrc = '/media/swatches/colour/preview/' + el.options[el.selectedIndex].text.replace(/ /g,'-').toLowerCase() + '-swatch.jpg';
                            placeHolderSrc = '/media/swatches/preview/select-colour-new.jpg';
                        }
                        else if (jQuery(el.up().down('.swatches-container')).hasClass("size"))
                        {
                            previewSrc = '/media/swatches/preview/' + el.options[el.selectedindex].text.replace(' ','-').toLowerCase() + '.jpg';
                            placeHolderSrc = '/media/swatches/preview/select-size.jpg';
                        }
                        else
                        {
                            previewSrc = '/media/swatches/preview/' + el.options[el.selectedIndex].text.replace(' ','-').toLowerCase() + '.jpg';
                            placeHolderSrc = '/media/swatches/preview/select-style.jpg';
                        }
                    }
                    else
                    {
                        previewSrc = '/media/swatches/preview/' + jQuery(el).next().find('label').clone().children().remove().end().text().trim().replace(/ /g,'-').toLowerCase() + '.jpg';
                        placeHolderSrc = '/media/swatches/preview/select-option.png';

                    }

                    new Ajax.Request(previewSrc,
                        {
                            onSuccess: function(response) {
                                $(preview[0]).down('img').writeAttribute('src', previewSrc);
                            },
                            onFailure: function(response) {
                                $(preview[0]).down('img').writeAttribute('src', previewSrc);
                            }
                        }
                    );

                }
            }

			var swatches = <?php echo Mage::helper('core')->jsonEncode($swatches); ?>;
			var optionClass = <?php echo Mage::helper('core')->jsonEncode($optionClass); ?>;

			function find_swatch(key, value) {

                var className = optionClass[key];
				for (var i in swatches) {
					if (swatches[i].key == className && swatches[i].value == value)
						return swatches[i];
				}
				return null;
			}
		
			function has_swatch_key(key) {
                var className = optionClass[key];
				for (var i in swatches) {
					if (swatches[i].key == className)
						return true;
				}
				return false;
			}
		
			function create_swatches(label, select) {
				// create swatches div, and append below the <select>
				var sw = new Element('div', {'class': 'swatches-container '+label});
				select.up().insertBefore(sw, select);
			
				// store these element to use later for recreate swatches
				select.swatchLabel = label;
				select.swatchElement = sw;
			
				// hide select
                if (label.indexOf('Colour') < 0)
                {
                    select.setStyle({position: 'absolute', top: '-9999px'})
                }

				$A(select.options).each(function(opt, i) {
					if (opt.getAttribute('value')) {
						var elm;
						var key = trim(opt.innerHTML);
					
						// remove price
						if (opt.getAttribute('price')) key = trim(key.replace(/\+([^+]+)$/, ''));
					
						var item = find_swatch(label, key);
                        //console.log(item);
						if (item) {
							elm = new Element('img', {
								src: '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA); ?>swatches/'+item.img.replace(/\s+/g, '-'),
								alt: opt.innerHTML, 
								title: opt.innerHTML, 
								'class': 'swatch-img'});

                        }
						else {
							//console.debug(label, key, swatches);
							
							// Custom style for cup size
							if (label == "Size Cups") {
								elm = new Element('a', {'class': 'swatch-span swatch-span-'+key.replace(/[^a-z0-9]|\s+|\r?\n|\r/gmi,''), 'style': 'width: 80px'});
							}
							else {
								elm = new Element('a', {'class': 'swatch-span swatch-span-'+key.replace(/[^a-z0-9]|\s+|\r?\n|\r/gmi,'')});
							}
							elm.update(opt.innerHTML);
						}
						elm.observe('click', function(event) {
							select.selectedIndex = i;
							fireEvent(select, 'change');
							var cur = sw.down('.current');
							if (cur) cur.removeClassName('current');
							elm.addClassName('current');

                            var preview = elm.up('dd').down('.swatchPreview');
                            if (preview === undefined) { return; }
                            if (elm.tagName === 'IMG')
                            {
                                var src = elm.readAttribute('src');
                                var previewSrc = src.substring(0, src.lastIndexOf("/"));
                                previewSrc += '/colour/preview' + src.substring(src.lastIndexOf("/"));
                                placeHolderSrc = '/media/swatches/preview/select-colour-new.jpg';
                            }
                            else
                            {
                                if (jQuery(elm.up()).hasClass("Size"))
                                {
                                    var src = elm.innerText;
                                    var previewSrc = src.replace(' ', '-').toLowerCase();
                                    previewSrc = '/media/swatches/preview/' + previewSrc + '.jpg';
                                    placeHolderSrc = '/media/swatches/preview/select-size.jpg';
                                }
                                else
                                {
                                    var src = elm.innerText;
                                    var previewSrc = src.replace(' ', '-').toLowerCase();
                                    previewSrc = '/media/swatches/preview/' + previewSrc + '.jpg';
                                    placeHolderSrc = '/media/swatches/preview/select-style.jpg';
                                }
								
								new Ajax.Request(previewSrc,
									{
										onSuccess: function(response) {
											preview.down('img').writeAttribute('src', previewSrc);
										},
										onFailure: function(response) {
											preview.down('img').writeAttribute('src', placeHolderSrc);
										}
									}
								);
								
                            }
						});
						sw.appendChild(elm);
					}
				});
			}
		
			function recreate_swatches_recursive(select) {
				// remove the old swatches
				if (select.swatchElement) {
					select.up().removeChild(select.swatchElement);
					select.swatchElement = null;
				}
			
				// create again
				if (!select.disabled)
					create_swatches(select.swatchLabel, select);
			
				// recursively recreate swatches for the next select
				if (select.nextSetting)
					recreate_swatches_recursive(select.nextSetting);
			}
		
			function fireEvent(element,event){
				if (document.createEventObject){
					// dispatch for IE
					var evt = document.createEventObject();
					return element.fireEvent('on'+event,evt)
				}
				else{
					// dispatch for firefox + others
					var evt = document.createEvent("HTMLEvents");
					evt.initEvent(event, true, true ); // event type,bubbling,cancelable
					return !element.dispatchEvent(evt);
				}
			}
		
			function trim(str) {
				return str.replace(/^\s\s*/, '').replace(/\s\s*$/, '');
			}
		
		
			$$('#product-options-wrapper dt').each(function(dt) {
			
				// get custom option's label
				var label = '';
				/*$A(dt.down('label').childNodes).each(function(node) {
					if (node.nodeType == 3) label += node.nodeValue;
				});*/
                label = dt.down('.realOptionTitle').innerHTML;
				label = trim(label);
			
				var dd = dt.next();
				var select = dd.down('select');
				if (select && has_swatch_key(label)) {
					create_swatches(label, select);
				
					// if configurable products, recreate swatches of the next select when the current select change
					if (select.hasClassName('super-attribute-select')) {
						select.observe('change', function() {
							setTimeout(function() {
								recreate_swatches_recursive(select.nextSetting);
							}, 100);
						});
					}
				}
                else {
                }
			});
after_swatches_created();
		}
		catch(e) {
			//alert("Color Swatches javascript error. Please report this error to support@galathemes.com. Error:" + e.message);
			console.log("Color Swatches javascript error. Please report this error to support@galathemes.com. Error:" + e.message);
		}
	});
</script>
