<!doctype html>
<html xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
		<?php echo $this->getChildHtml('global_notices') ?>
		<?php echo $this->getChildHtml('header') ?>
		<?php echo $this->getChildHtml('breadcrumbs') ?>		
		<div class="wrapper column-1">
			<?php echo $this->getChildHtml('global_messages') ?>
			<?php echo $this->getChildHtml('content') ?>
		</div>	
		<?php echo $this->getChildHtml('footer') ?>
		<?php echo $this->getChildHtml('global_cookie_notice') ?>
		<?php echo $this->getChildHtml('before_body_end') ?>
		<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>