<!doctype html>
<html xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
		<?php echo $this->getChildHtml('global_notices') ?>
		<?php echo $this->getChildHtml('header') ?>
		<?php echo $this->getChildHtml('breadcrumbs') ?>
		<?php echo $this->getChildHtml('full_width_title') ?>
        <div class="wrapper col2-right-layout">
	        <?php echo $this->getChildHtml('global_messages') ?>
                <div class="col-main">
                    <?php echo $this->getChildHtml('content') ?>
                </div>
                <aside><?php echo $this->getChildHtml('right') ?></aside>
            </div>
        </div>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>