<!doctype html>
<html xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass()?' class="'.$this->getBodyClass().'"':'' ?>>
<?php echo $this->getChildHtml('after_body_start') ?>
		<?php echo $this->getChildHtml('global_notices') ?>
		<?php echo $this->getChildHtml('header') ?>
		
		<?php echo $this->getChildHtml('newReferenceBlock') ?>


		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('plus_size_banner')->toHtml(); ?> 
		
		<?php echo $this->getChildHtml('full_width_title') ?>
		<div class="category-full-width">
	        <div class="wrapper col2-left-layout">
		        <?php echo $this->getChildHtml('global_messages') ?>
	                <div class="col-main">
	                    <?php echo $this->getChildHtml('content') ?>
	                </div>
	                <aside><?php echo $this->getChildHtml('left') ?></aside>
					<div class="category-background-left"></div><div class="category-background-right"></div>
	            </div>
			</div>
        </div>

        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('global_cookie_notice') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>