<div id="forgot-password" class="forgot-password-popup" style="display:none">	
<h4 class="modal-title">Forgotten your password?<a class="close-modal" href="javascript:void(0);" onclick="jQuery.fancybox.close();"><i class="fa fa-times-circle"></i></a></h4>
<div class="modal-content">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
<div class="fieldset">
<p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
<ul class="form-list">
<li>
<!-- <label class="required">Email address <i>*</i></label> -->
<input type="text" placeholder="Enter your email address" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
</li>
<?php echo $this->getChildHtml('form.additional.info'); ?>
<button type="submit" title="<?php echo $this->__('Submit') ?>" class="button"><?php echo $this->__('Submit') ?></button>
</ul>
</div>
</form>
<script type="text/javascript">
//<![CDATA[
var dataForm = new VarienForm('form-validate', true);
//]]>
</script>
</div><!-- END modal content -->
</div>